language: python
sudo: true

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

before_script:
  - export TZ=Europe/Vienna

install:
  - pip install coverage
  - pip install coveralls
  - pip install pyramid==1.9.4
  - |
    if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then
        pip install repoze.zcml==0.4
        pip install repoze.workflow==0.6.1
    else
        pip install repoze.zcml==1.1
        pip install repoze.workflow==1.1
    fi
  - pip install https://github.com/conestack/node.ext.ugm/archive/master.zip
  - pip install https://github.com/conestack/yafowil/archive/master.zip
  - pip install https://github.com/conestack/cone.tile/archive/master.zip
  - pip install https://github.com/conestack/cone.app/archive/master.zip
  - pip install -e .[test]

script:
  - python -m cone.ugm.tests.__init__
  - coverage run --source src/cone/ugm -m cone.ugm.tests.__init__
  - coverage report

after_success:
  - coveralls
